# Generated by Django 5.2 on 2025-04-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', '🔴 높음'), ('medium', '🟠 중간'), ('low', '🟢 낮음')], default='medium', max_length=10),
        ),
    ]
